---
apiVersion: v1
kind: Service
metadata:
  name: movies-stream-app
  labels:
    app: movies-stream-app
spec:
  type: NodePort
  selector:
    app: movies-stream-app
  ports:
  - protocol: TCP
    port: 8010
    name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: movies-stream-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: movies-stream-app
    spec:
      containers:
      - name: movies-stream-app
        image: movies-stream
        ports:
        - containerPort: 8010
        livenessProbe:
          httpGet:
            path: /
            port: 8010
          initialDelaySeconds: 30
          timeoutSeconds: 1